global:
  scrape_interval: 10s

rule_files:
  - /etc/prometheus/prometheus-alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['ras_prometheus:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['ras_postgres:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['ras_redis:9121']

  # ✅ Base Service metrics
  - job_name: 'base-service'
    static_configs:
      - targets: ['ras_base_service:8080']

  # ✅ Validator Service metrics
  - job_name: 'validator-service'
    static_configs:
      - targets: ['ras_validator_service:8081']
